[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "mtofr_sim"
version = "0.0.1"
description = "A simulator for mission-type orders for robotics"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "pyyaml"
]

[tool.setuptools.packages.find]
where = ["src"]